//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCide.WPF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SCide.WPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $OBJECT=Form
        ///
        ///Option Explicit
        ///
        ///&apos; Base VBscript template for Commence detail forms.
        ///&apos; See your Commence documentation for more information about scripting.
        ///
        ///Sub Form_OnLoad()
        ///End Sub
        ///
        ///Sub Form_OnSave()
        ///End Sub
        ///
        ///Sub Form_OnCancel()
        ///End Sub
        ///
        ///Sub Form_OnEnterTab(ByVal TabName)
        ///End Sub
        ///
        ///Sub Form_OnLeaveTab(ByVal TabName)
        ///End Sub
        ///
        ///Sub Form_OnEnterField(ByVal FieldName)
        ///End Sub
        ///
        ///Sub Form_OnLeaveField(ByVal FieldName)
        ///End Sub
        ///
        ///Sub Form_OnActiveXControlEvent(ByVal ControlName, ByVal Event [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DefaultIDFScript {
            get {
                return ResourceManager.GetString("DefaultIDFScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $OBJECT=Form
        ///
        ///Option Explicit
        ///
        ///&apos; Base VBscript template for Commence detail forms.
        ///Sub Form_OnEnterTab(ByVal TabName)
        ///	dim numVal, txtVal
        ///	numVal = &amp;H8F0 + 42
        ///	txtVal = &quot;Hello World!&quot;
        ///	txtVal = txtVal &amp; &quot; by Vovin IT Services.&quot;
        ///End Sub.
        /// </summary>
        public static string SciSampleCode {
            get {
                return ResourceManager.GetString("SciSampleCode", resourceCulture);
            }
        }
    }
}
